defmodule CCXT.Types do
  @moduledoc "Convenience aliases for CCXT type modules. Auto-generated from priv/ccxt/ts/src/base/types.ts."

  defmacro __using__(_opts) do
    quote do
      alias CCXT.Types.Account
      alias CCXT.Types.BalanceAccount
      alias CCXT.Types.BalanceEntry
      alias CCXT.Types.Balances
      alias CCXT.Types.Bool
      alias CCXT.Types.BorrowInterest
      alias CCXT.Types.CancellationRequest
      alias CCXT.Types.ConstructorArgs
      alias CCXT.Types.Conversion
      alias CCXT.Types.CrossBorrowRate
      alias CCXT.Types.CrossBorrowRates
      alias CCXT.Types.Currencies
      alias CCXT.Types.Currency
      alias CCXT.Types.CurrencyInterface
      alias CCXT.Types.DepositAddress
      alias CCXT.Types.DepositWithdrawFee
      alias CCXT.Types.DepositWithdrawFeeNetwork
      alias CCXT.Types.Dict
      alias CCXT.Types.Dictionary
      alias CCXT.Types.Fee
      alias CCXT.Types.FeeInterface
      alias CCXT.Types.FundingHistory
      alias CCXT.Types.FundingRate
      alias CCXT.Types.FundingRateHistory
      alias CCXT.Types.FundingRates
      alias CCXT.Types.Greeks
      alias CCXT.Types.ImplicitReturnType
      alias CCXT.Types.IndexType
      alias CCXT.Types.Int
      alias CCXT.Types.IsolatedBorrowRate
      alias CCXT.Types.IsolatedBorrowRates
      alias CCXT.Types.LastPrice
      alias CCXT.Types.LastPrices
      alias CCXT.Types.LedgerEntry
      alias CCXT.Types.Leverage
      alias CCXT.Types.Leverages
      alias CCXT.Types.LeverageTier
      alias CCXT.Types.LeverageTiers
      alias CCXT.Types.Liquidation
      alias CCXT.Types.List
      alias CCXT.Types.LongShortRatio
      alias CCXT.Types.MarginMode
      alias CCXT.Types.MarginModes
      alias CCXT.Types.MarginModification
      alias CCXT.Types.Market
      alias CCXT.Types.MarketInterface
      alias CCXT.Types.MarketMarginModes
      alias CCXT.Types.MarketType
      alias CCXT.Types.MinMax
      alias CCXT.Types.NullableDict
      alias CCXT.Types.NullableList
      alias CCXT.Types.Num
      alias CCXT.Types.OHLCV
      alias CCXT.Types.OHLCVC
      alias CCXT.Types.OpenInterest
      alias CCXT.Types.OpenInterests
      alias CCXT.Types.Option
      alias CCXT.Types.OptionChain
      alias CCXT.Types.Order
      alias CCXT.Types.OrderBook
      alias CCXT.Types.OrderBooks
      alias CCXT.Types.OrderRequest
      alias CCXT.Types.OrderSide
      alias CCXT.Types.OrderType
      alias CCXT.Types.PartialBalances
      alias CCXT.Types.Position
      alias CCXT.Types.Str
      alias CCXT.Types.Strings
      alias CCXT.Types.SubType
      alias CCXT.Types.Ticker
      alias CCXT.Types.Tickers
      alias CCXT.Types.Trade
      alias CCXT.Types.TradingFeeInterface
      alias CCXT.Types.TradingFees
      alias CCXT.Types.Transaction
      alias CCXT.Types.TransferEntry
      alias CCXT.Types.WithdrawalResponse
    end
  end
end
