defmodule CCXT.Types.Schema.BorrowInterest do
  @moduledoc """
  Auto-generated schema for `CCXT.Types.BorrowInterest`.

  Source: priv/ccxt/ts/src/base/types.ts

  ## Fields

  - `raw` - any()
  - `symbol` - String.t() | nil (optional)
  - `currency` - String.t() | nil (optional)
  - `interest` - number() (optional)
  - `interest_rate` - number() (optional)
  - `amount_borrowed` - number() (optional)
  - `margin_mode` - String.t() | nil (optional)
  - `timestamp` - integer() | nil (optional)
  - `datetime` - String.t() | nil (optional)

  ## Usage

  This module is used by `CCXT.Types.BorrowInterest`:

      defmodule CCXT.Types.BorrowInterest do
        use CCXT.Types.Schema.BorrowInterest
      end

  Do not edit this file manually - it will be overwritten by `mix ccxt.gen.types`.

  """

  @fields [
    %{name: :raw, optional: false, source: "info", type: "any()"},
    %{name: :symbol, optional: true, source: "symbol", type: "String.t() | nil"},
    %{name: :currency, optional: true, source: "currency", type: "String.t() | nil"},
    %{name: :interest, optional: true, source: "interest", type: "number()"},
    %{name: :interest_rate, optional: true, source: "interestRate", type: "number()"},
    %{name: :amount_borrowed, optional: true, source: "amountBorrowed", type: "number()"},
    %{name: :margin_mode, optional: true, source: "marginMode", type: "String.t() | nil"},
    %{name: :timestamp, optional: true, source: "timestamp", type: "integer() | nil"},
    %{name: :datetime, optional: true, source: "datetime", type: "String.t() | nil"}
  ]
  @type_spec_str """
  %__MODULE__{
    raw: any(),
    symbol: String.t() | nil,
    currency: String.t() | nil,
    interest: number() | nil,
    interest_rate: number() | nil,
    amount_borrowed: number() | nil,
    margin_mode: String.t() | nil,
    timestamp: integer() | nil,
    datetime: String.t() | nil
  }
  """
  @type_spec Code.string_to_quoted!(@type_spec_str)

  defmacro __using__(opts) do
    fields = @fields
    type_spec = @type_spec
    struct_defaults = Keyword.get(opts, :struct_defaults, [])
    field_names = Enum.map(fields, & &1.name)

    struct_fields =
      Enum.map(field_names, fn name ->
        if Keyword.has_key?(struct_defaults, name) do
          {name, Keyword.fetch!(struct_defaults, name)}
        else
          name
        end
      end)

    quote do
      import CCXT.Types.Helpers, only: [get_value: 2, get_camel_value: 3]

      @fields unquote(Macro.escape(fields))
      @type_spec unquote(Macro.escape(type_spec))
      @type t :: unquote(type_spec)
      defstruct unquote(struct_fields)
      @spec from_map(map()) :: t()
      def from_map(map) when is_map(map) do
        %__MODULE__{
          raw: get_camel_value(map, :raw, :info),
          symbol: get_value(map, :symbol),
          currency: get_value(map, :currency),
          interest: get_value(map, :interest),
          interest_rate: get_camel_value(map, :interest_rate, :interestRate),
          amount_borrowed: get_camel_value(map, :amount_borrowed, :amountBorrowed),
          margin_mode: get_camel_value(map, :margin_mode, :marginMode),
          timestamp: get_value(map, :timestamp),
          datetime: get_value(map, :datetime)
        }
      end

      defoverridable from_map: 1
    end
  end
end
