defmodule CCXT.Types.Schema.LedgerEntry do
  @moduledoc """
  Auto-generated schema for `CCXT.Types.LedgerEntry`.

  Source: priv/ccxt/ts/src/base/types.ts

  ## Fields

  - `raw` - any()
  - `id` - String.t() | nil (optional)
  - `timestamp` - number() (optional)
  - `datetime` - String.t() | nil (optional)
  - `direction` - String.t() | nil (optional)
  - `account` - String.t() | nil (optional)
  - `reference_id` - String.t() | nil (optional)
  - `reference_account` - String.t() | nil (optional)
  - `type` - String.t() | nil (optional)
  - `currency` - String.t() | nil (optional)
  - `amount` - number() (optional)
  - `before` - number() (optional)
  - `after` - number() (optional)
  - `status` - String.t() | nil (optional)
  - `fee` - CCXT.Types.FeeInterface.t() | nil (optional)

  ## Usage

  This module is used by `CCXT.Types.LedgerEntry`:

      defmodule CCXT.Types.LedgerEntry do
        use CCXT.Types.Schema.LedgerEntry
      end

  Do not edit this file manually - it will be overwritten by `mix ccxt.gen.types`.

  """

  @fields [
    %{name: :raw, optional: false, source: "info", type: "any()"},
    %{name: :id, optional: true, source: "id", type: "String.t() | nil"},
    %{name: :timestamp, optional: true, source: "timestamp", type: "number()"},
    %{name: :datetime, optional: true, source: "datetime", type: "String.t() | nil"},
    %{name: :direction, optional: true, source: "direction", type: "String.t() | nil"},
    %{name: :account, optional: true, source: "account", type: "String.t() | nil"},
    %{name: :reference_id, optional: true, source: "referenceId", type: "String.t() | nil"},
    %{
      name: :reference_account,
      optional: true,
      source: "referenceAccount",
      type: "String.t() | nil"
    },
    %{name: :type, optional: true, source: "type", type: "String.t() | nil"},
    %{name: :currency, optional: true, source: "currency", type: "String.t() | nil"},
    %{name: :amount, optional: true, source: "amount", type: "number()"},
    %{name: :before, optional: true, source: "before", type: "number()"},
    %{name: :after, optional: true, source: "after", type: "number()"},
    %{name: :status, optional: true, source: "status", type: "String.t() | nil"},
    %{name: :fee, optional: true, source: "fee", type: "CCXT.Types.FeeInterface.t() | nil"}
  ]
  @type_spec_str """
  %__MODULE__{
    raw: any(),
    id: String.t() | nil,
    timestamp: number() | nil,
    datetime: String.t() | nil,
    direction: String.t() | nil,
    account: String.t() | nil,
    reference_id: String.t() | nil,
    reference_account: String.t() | nil,
    type: String.t() | nil,
    currency: String.t() | nil,
    amount: number() | nil,
    before: number() | nil,
    after: number() | nil,
    status: String.t() | nil,
    fee: CCXT.Types.FeeInterface.t() | nil
  }
  """
  @type_spec Code.string_to_quoted!(@type_spec_str)

  defmacro __using__(opts) do
    fields = @fields
    type_spec = @type_spec
    struct_defaults = Keyword.get(opts, :struct_defaults, [])
    field_names = Enum.map(fields, & &1.name)

    struct_fields =
      Enum.map(field_names, fn name ->
        if Keyword.has_key?(struct_defaults, name) do
          {name, Keyword.fetch!(struct_defaults, name)}
        else
          name
        end
      end)

    quote do
      import CCXT.Types.Helpers, only: [get_value: 2, get_camel_value: 3]

      @fields unquote(Macro.escape(fields))
      @type_spec unquote(Macro.escape(type_spec))
      @type t :: unquote(type_spec)
      defstruct unquote(struct_fields)
      @spec from_map(map()) :: t()
      def from_map(map) when is_map(map) do
        %__MODULE__{
          raw: get_camel_value(map, :raw, :info),
          id: get_value(map, :id),
          timestamp: get_value(map, :timestamp),
          datetime: get_value(map, :datetime),
          direction: get_value(map, :direction),
          account: get_value(map, :account),
          reference_id: get_camel_value(map, :reference_id, :referenceId),
          reference_account: get_camel_value(map, :reference_account, :referenceAccount),
          type: get_value(map, :type),
          currency: get_value(map, :currency),
          amount: get_value(map, :amount),
          before: get_value(map, :before),
          after: get_value(map, :after),
          status: get_value(map, :status),
          fee: get_value(map, :fee)
        }
      end

      defoverridable from_map: 1
    end
  end
end
