defmodule CCXT.Types.Schema.Liquidation do
  @moduledoc """
  Auto-generated schema for `CCXT.Types.Liquidation`.

  Source: priv/ccxt/ts/src/base/types.ts

  ## Fields

  - `raw` - any()
  - `symbol` - String.t()
  - `timestamp` - number() (optional)
  - `datetime` - String.t() | nil (optional)
  - `price` - number()
  - `base_value` - number() (optional)
  - `quote_value` - number() (optional)
  - `contracts` - number() (optional)
  - `contract_size` - number() (optional)
  - `side` - String.t() | nil (optional)

  ## Usage

  This module is used by `CCXT.Types.Liquidation`:

      defmodule CCXT.Types.Liquidation do
        use CCXT.Types.Schema.Liquidation
      end

  Do not edit this file manually - it will be overwritten by `mix ccxt.gen.types`.

  """

  @fields [
    %{name: :raw, optional: false, source: "info", type: "any()"},
    %{name: :symbol, optional: false, source: "symbol", type: "String.t()"},
    %{name: :timestamp, optional: true, source: "timestamp", type: "number()"},
    %{name: :datetime, optional: true, source: "datetime", type: "String.t() | nil"},
    %{name: :price, optional: false, source: "price", type: "number()"},
    %{name: :base_value, optional: true, source: "baseValue", type: "number()"},
    %{name: :quote_value, optional: true, source: "quoteValue", type: "number()"},
    %{name: :contracts, optional: true, source: "contracts", type: "number()"},
    %{name: :contract_size, optional: true, source: "contractSize", type: "number()"},
    %{name: :side, optional: true, source: "side", type: "String.t() | nil"}
  ]
  @type_spec_str """
  %__MODULE__{
    raw: any(),
    symbol: String.t(),
    timestamp: number() | nil,
    datetime: String.t() | nil,
    price: number(),
    base_value: number() | nil,
    quote_value: number() | nil,
    contracts: number() | nil,
    contract_size: number() | nil,
    side: String.t() | nil
  }
  """
  @type_spec Code.string_to_quoted!(@type_spec_str)

  defmacro __using__(opts) do
    fields = @fields
    type_spec = @type_spec
    struct_defaults = Keyword.get(opts, :struct_defaults, [])
    field_names = Enum.map(fields, & &1.name)

    struct_fields =
      Enum.map(field_names, fn name ->
        if Keyword.has_key?(struct_defaults, name) do
          {name, Keyword.fetch!(struct_defaults, name)}
        else
          name
        end
      end)

    quote do
      import CCXT.Types.Helpers, only: [get_value: 2, get_camel_value: 3]

      @fields unquote(Macro.escape(fields))
      @type_spec unquote(Macro.escape(type_spec))
      @type t :: unquote(type_spec)
      defstruct unquote(struct_fields)
      @spec from_map(map()) :: t()
      def from_map(map) when is_map(map) do
        %__MODULE__{
          raw: get_camel_value(map, :raw, :info),
          symbol: get_value(map, :symbol),
          timestamp: get_value(map, :timestamp),
          datetime: get_value(map, :datetime),
          price: get_value(map, :price),
          base_value: get_camel_value(map, :base_value, :baseValue),
          quote_value: get_camel_value(map, :quote_value, :quoteValue),
          contracts: get_value(map, :contracts),
          contract_size: get_camel_value(map, :contract_size, :contractSize),
          side: get_value(map, :side)
        }
      end

      defoverridable from_map: 1
    end
  end
end
