defmodule CCXT.Types.Schema.Ticker do
  @moduledoc """
  Auto-generated schema for `CCXT.Types.Ticker`.

  Source: priv/ccxt/ts/src/base/types.ts

  ## Fields

  - `symbol` - Trading pair identifier (e.g. "BTC/USDT"). String.t()
  - `raw` - Raw exchange response data. any()
  - `timestamp` - Unix timestamp in milliseconds. integer() | nil
  - `datetime` - ISO 8601 datetime string. String.t() | nil
  - `high` - Highest price in the last 24 hours. number() | nil
  - `low` - Lowest price in the last 24 hours. number() | nil
  - `bid` - Current best bid price. number() | nil
  - `bid_volume` - Volume available at the best bid price. number() | nil
  - `ask` - Current best ask price. number() | nil
  - `ask_volume` - Volume available at the best ask price. number() | nil
  - `vwap` - Volume-weighted average price over 24 hours. number() | nil
  - `open` - Opening price 24 hours ago. number() | nil
  - `close` - Closing price (same as `last` for most exchanges). number() | nil
  - `last` - Last traded price. number() | nil
  - `previous_close` - Previous period's closing price. number() | nil
  - `change` - Absolute price change over 24 hours. number() | nil
  - `percentage` - Percentage price change over 24 hours. number() | nil
  - `average` - Average price over 24 hours. number() | nil
  - `quote_volume` - 24h trading volume in quote currency. number() | nil
  - `base_volume` - 24h trading volume in base currency. number() | nil
  - `index_price` - Underlying index price (derivatives only). number() | nil
  - `mark_price` - Mark price used for margin calculations (derivatives only). number() | nil

  ## Usage

  This module is used by `CCXT.Types.Ticker`:

      defmodule CCXT.Types.Ticker do
        use CCXT.Types.Schema.Ticker
      end

  Do not edit this file manually - it will be overwritten by `mix ccxt.gen.types`.

  """

  Module.register_attribute(__MODULE__, :fields, persist: true)

  @fields [
    %{name: :symbol, optional: false, source: "symbol", type: "String.t()"},
    %{name: :raw, optional: false, source: "info", type: "any()"},
    %{name: :timestamp, optional: false, source: "timestamp", type: "integer() | nil"},
    %{name: :datetime, optional: false, source: "datetime", type: "String.t() | nil"},
    %{name: :high, optional: false, source: "high", type: "number() | nil"},
    %{name: :low, optional: false, source: "low", type: "number() | nil"},
    %{name: :bid, optional: false, source: "bid", type: "number() | nil"},
    %{name: :bid_volume, optional: false, source: "bidVolume", type: "number() | nil"},
    %{name: :ask, optional: false, source: "ask", type: "number() | nil"},
    %{name: :ask_volume, optional: false, source: "askVolume", type: "number() | nil"},
    %{name: :vwap, optional: false, source: "vwap", type: "number() | nil"},
    %{name: :open, optional: false, source: "open", type: "number() | nil"},
    %{name: :close, optional: false, source: "close", type: "number() | nil"},
    %{name: :last, optional: false, source: "last", type: "number() | nil"},
    %{name: :previous_close, optional: false, source: "previousClose", type: "number() | nil"},
    %{name: :change, optional: false, source: "change", type: "number() | nil"},
    %{name: :percentage, optional: false, source: "percentage", type: "number() | nil"},
    %{name: :average, optional: false, source: "average", type: "number() | nil"},
    %{name: :quote_volume, optional: false, source: "quoteVolume", type: "number() | nil"},
    %{name: :base_volume, optional: false, source: "baseVolume", type: "number() | nil"},
    %{name: :index_price, optional: false, source: "indexPrice", type: "number() | nil"},
    %{name: :mark_price, optional: false, source: "markPrice", type: "number() | nil"}
  ]
  @type_spec_str """
  %__MODULE__{
    symbol: String.t(),
    raw: any(),
    timestamp: integer() | nil,
    datetime: String.t() | nil,
    high: number() | nil,
    low: number() | nil,
    bid: number() | nil,
    bid_volume: number() | nil,
    ask: number() | nil,
    ask_volume: number() | nil,
    vwap: number() | nil,
    open: number() | nil,
    close: number() | nil,
    last: number() | nil,
    previous_close: number() | nil,
    change: number() | nil,
    percentage: number() | nil,
    average: number() | nil,
    quote_volume: number() | nil,
    base_volume: number() | nil,
    index_price: number() | nil,
    mark_price: number() | nil
  }
  """
  @type_spec Code.string_to_quoted!(@type_spec_str)

  defmacro __using__(opts) do
    fields = @fields
    type_spec = @type_spec
    struct_defaults = Keyword.get(opts, :struct_defaults, [])
    field_names = Enum.map(fields, & &1.name)

    struct_fields =
      Enum.map(field_names, fn name ->
        if Keyword.has_key?(struct_defaults, name) do
          {name, Keyword.fetch!(struct_defaults, name)}
        else
          name
        end
      end)

    quote do
      import CCXT.Types.Helpers, only: [get_value: 2, get_camel_value: 3]

      @fields unquote(Macro.escape(fields))
      @type_spec unquote(Macro.escape(type_spec))
      @type t :: unquote(type_spec)
      defstruct unquote(struct_fields)
      @spec from_map(map()) :: t()
      def from_map(map) when is_map(map) do
        %__MODULE__{
          symbol: get_value(map, :symbol),
          raw: get_camel_value(map, :raw, :info),
          timestamp: get_value(map, :timestamp),
          datetime: get_value(map, :datetime),
          high: get_value(map, :high),
          low: get_value(map, :low),
          bid: get_value(map, :bid),
          bid_volume: get_camel_value(map, :bid_volume, :bidVolume),
          ask: get_value(map, :ask),
          ask_volume: get_camel_value(map, :ask_volume, :askVolume),
          vwap: get_value(map, :vwap),
          open: get_value(map, :open),
          close: get_value(map, :close),
          last: get_value(map, :last),
          previous_close: get_camel_value(map, :previous_close, :previousClose),
          change: get_value(map, :change),
          percentage: get_value(map, :percentage),
          average: get_value(map, :average),
          quote_volume: get_camel_value(map, :quote_volume, :quoteVolume),
          base_volume: get_camel_value(map, :base_volume, :baseVolume),
          index_price: get_camel_value(map, :index_price, :indexPrice),
          mark_price: get_camel_value(map, :mark_price, :markPrice)
        }
      end

      defoverridable from_map: 1
    end
  end
end
