defmodule CCXT.Types.Schema.Trade do
  @moduledoc """
  Auto-generated schema for `CCXT.Types.Trade`.

  Source: priv/ccxt/ts/src/base/types.ts

  ## Fields

  - `raw` - Raw exchange response data. any()
  - `amount` - Trade quantity in base currency. number() | nil
  - `datetime` - ISO 8601 datetime of the trade. String.t() | nil
  - `id` - Exchange-assigned trade identifier. String.t() | nil
  - `order_id` - Order identifier this trade belongs to. String.t() | nil
  - `price` - Execution price. number()
  - `timestamp` - Unix timestamp in milliseconds. integer() | nil
  - `type` - Order type that generated this trade ("limit", "market"). String.t() | nil
  - `side` - Trade side: "buy" or "sell". String.t() | nil
  - `symbol` - Trading pair identifier (e.g. "BTC/USDT"). String.t() | nil
  - `taker_or_maker` - Liquidity side: "taker" or "maker". String.t() | nil
  - `cost` - Total cost of the trade (price * amount). number() | nil
  - `fee` - Fee charged for this trade. CCXT.Types.FeeInterface.t() | nil

  ## Usage

  This module is used by `CCXT.Types.Trade`:

      defmodule CCXT.Types.Trade do
        use CCXT.Types.Schema.Trade
      end

  Do not edit this file manually - it will be overwritten by `mix ccxt.gen.types`.

  """

  Module.register_attribute(__MODULE__, :fields, persist: true)

  @fields [
    %{name: :raw, optional: false, source: "info", type: "any()"},
    %{name: :amount, optional: false, source: "amount", type: "number() | nil"},
    %{name: :datetime, optional: false, source: "datetime", type: "String.t() | nil"},
    %{name: :id, optional: false, source: "id", type: "String.t() | nil"},
    %{name: :order_id, optional: false, source: "order", type: "String.t() | nil"},
    %{name: :price, optional: false, source: "price", type: "number()"},
    %{name: :timestamp, optional: false, source: "timestamp", type: "integer() | nil"},
    %{name: :type, optional: false, source: "type", type: "String.t() | nil"},
    %{name: :side, optional: false, source: "side", type: "String.t() | nil"},
    %{name: :symbol, optional: false, source: "symbol", type: "String.t() | nil"},
    %{name: :taker_or_maker, optional: false, source: "takerOrMaker", type: "String.t() | nil"},
    %{name: :cost, optional: false, source: "cost", type: "number() | nil"},
    %{name: :fee, optional: false, source: "fee", type: "CCXT.Types.FeeInterface.t() | nil"}
  ]
  @type_spec_str """
  %__MODULE__{
    raw: any(),
    amount: number() | nil,
    datetime: String.t() | nil,
    id: String.t() | nil,
    order_id: String.t() | nil,
    price: number(),
    timestamp: integer() | nil,
    type: String.t() | nil,
    side: String.t() | nil,
    symbol: String.t() | nil,
    taker_or_maker: String.t() | nil,
    cost: number() | nil,
    fee: CCXT.Types.FeeInterface.t() | nil
  }
  """
  @type_spec Code.string_to_quoted!(@type_spec_str)

  defmacro __using__(opts) do
    fields = @fields
    type_spec = @type_spec
    struct_defaults = Keyword.get(opts, :struct_defaults, [])
    field_names = Enum.map(fields, & &1.name)

    struct_fields =
      Enum.map(field_names, fn name ->
        if Keyword.has_key?(struct_defaults, name) do
          {name, Keyword.fetch!(struct_defaults, name)}
        else
          name
        end
      end)

    quote do
      import CCXT.Types.Helpers, only: [get_value: 2, get_camel_value: 3]

      @fields unquote(Macro.escape(fields))
      @type_spec unquote(Macro.escape(type_spec))
      @type t :: unquote(type_spec)
      defstruct unquote(struct_fields)
      @spec from_map(map()) :: t()
      def from_map(map) when is_map(map) do
        %__MODULE__{
          raw: get_camel_value(map, :raw, :info),
          amount: get_value(map, :amount),
          datetime: get_value(map, :datetime),
          id: get_value(map, :id),
          order_id: get_camel_value(map, :order_id, :order),
          price: get_value(map, :price),
          timestamp: get_value(map, :timestamp),
          type: get_value(map, :type),
          side: get_value(map, :side),
          symbol: get_value(map, :symbol),
          taker_or_maker: get_camel_value(map, :taker_or_maker, :takerOrMaker),
          cost: get_value(map, :cost),
          fee: get_value(map, :fee)
        }
      end

      defoverridable from_map: 1
    end
  end
end
