defmodule CCXT.Types.Schema.Transaction do
  @moduledoc """
  Auto-generated schema for `CCXT.Types.Transaction`.

  Source: priv/ccxt/ts/src/base/types.ts

  ## Fields

  - `raw` - Raw exchange response data. any()
  - `id` - Exchange-assigned transaction identifier. String.t() | nil
  - `txid` - Blockchain transaction hash/ID. String.t() | nil
  - `timestamp` - Unix timestamp in milliseconds. integer() | nil
  - `datetime` - ISO 8601 datetime string. String.t() | nil
  - `address` - Deposit/withdrawal address. String.t() | nil
  - `address_from` - Source address (for withdrawals). String.t() | nil
  - `address_to` - Destination address (for deposits). String.t() | nil
  - `tag` - Address tag/memo (e.g. for XRP, XLM). String.t() | nil
  - `tag_from` - Source address tag. String.t() | nil
  - `tag_to` - Destination address tag. String.t() | nil
  - `type` - Transaction type: "deposit" or "withdrawal". String.t() | nil
  - `amount` - Transaction amount. number() | nil
  - `currency` - Currency code (e.g. "BTC"). String.t() | nil
  - `status` - Transaction status: "pending", "ok", "failed", "canceled". String.t() | nil
  - `updated` - Last update timestamp in milliseconds. integer() | nil
  - `fee` - Transaction fee. CCXT.Types.FeeInterface.t() | nil
  - `network` - Blockchain network (e.g. "ETH", "TRC20"). String.t() | nil
  - `comment` - User-provided transaction comment/note. String.t() | nil
  - `internal` - Whether this is an internal transfer (not on-chain). boolean() | nil

  ## Usage

  This module is used by `CCXT.Types.Transaction`:

      defmodule CCXT.Types.Transaction do
        use CCXT.Types.Schema.Transaction
      end

  Do not edit this file manually - it will be overwritten by `mix ccxt.gen.types`.

  """

  Module.register_attribute(__MODULE__, :fields, persist: true)

  @fields [
    %{name: :raw, optional: false, source: "info", type: "any()"},
    %{name: :id, optional: false, source: "id", type: "String.t() | nil"},
    %{name: :txid, optional: false, source: "txid", type: "String.t() | nil"},
    %{name: :timestamp, optional: false, source: "timestamp", type: "integer() | nil"},
    %{name: :datetime, optional: false, source: "datetime", type: "String.t() | nil"},
    %{name: :address, optional: false, source: "address", type: "String.t() | nil"},
    %{name: :address_from, optional: false, source: "addressFrom", type: "String.t() | nil"},
    %{name: :address_to, optional: false, source: "addressTo", type: "String.t() | nil"},
    %{name: :tag, optional: false, source: "tag", type: "String.t() | nil"},
    %{name: :tag_from, optional: false, source: "tagFrom", type: "String.t() | nil"},
    %{name: :tag_to, optional: false, source: "tagTo", type: "String.t() | nil"},
    %{name: :type, optional: false, source: "type", type: "String.t() | nil"},
    %{name: :amount, optional: false, source: "amount", type: "number() | nil"},
    %{name: :currency, optional: false, source: "currency", type: "String.t() | nil"},
    %{name: :status, optional: false, source: "status", type: "String.t() | nil"},
    %{name: :updated, optional: false, source: "updated", type: "integer() | nil"},
    %{name: :fee, optional: false, source: "fee", type: "CCXT.Types.FeeInterface.t() | nil"},
    %{name: :network, optional: false, source: "network", type: "String.t() | nil"},
    %{name: :comment, optional: false, source: "comment", type: "String.t() | nil"},
    %{name: :internal, optional: false, source: "internal", type: "boolean() | nil"}
  ]
  @type_spec_str """
  %__MODULE__{
    raw: any(),
    id: String.t() | nil,
    txid: String.t() | nil,
    timestamp: integer() | nil,
    datetime: String.t() | nil,
    address: String.t() | nil,
    address_from: String.t() | nil,
    address_to: String.t() | nil,
    tag: String.t() | nil,
    tag_from: String.t() | nil,
    tag_to: String.t() | nil,
    type: String.t() | nil,
    amount: number() | nil,
    currency: String.t() | nil,
    status: String.t() | nil,
    updated: integer() | nil,
    fee: CCXT.Types.FeeInterface.t() | nil,
    network: String.t() | nil,
    comment: String.t() | nil,
    internal: boolean() | nil
  }
  """
  @type_spec Code.string_to_quoted!(@type_spec_str)

  defmacro __using__(opts) do
    fields = @fields
    type_spec = @type_spec
    struct_defaults = Keyword.get(opts, :struct_defaults, [])
    field_names = Enum.map(fields, & &1.name)

    struct_fields =
      Enum.map(field_names, fn name ->
        if Keyword.has_key?(struct_defaults, name) do
          {name, Keyword.fetch!(struct_defaults, name)}
        else
          name
        end
      end)

    quote do
      import CCXT.Types.Helpers, only: [get_value: 2, get_camel_value: 3]

      @fields unquote(Macro.escape(fields))
      @type_spec unquote(Macro.escape(type_spec))
      @type t :: unquote(type_spec)
      defstruct unquote(struct_fields)
      @spec from_map(map()) :: t()
      def from_map(map) when is_map(map) do
        %__MODULE__{
          raw: get_camel_value(map, :raw, :info),
          id: get_value(map, :id),
          txid: get_value(map, :txid),
          timestamp: get_value(map, :timestamp),
          datetime: get_value(map, :datetime),
          address: get_value(map, :address),
          address_from: get_camel_value(map, :address_from, :addressFrom),
          address_to: get_camel_value(map, :address_to, :addressTo),
          tag: get_value(map, :tag),
          tag_from: get_camel_value(map, :tag_from, :tagFrom),
          tag_to: get_camel_value(map, :tag_to, :tagTo),
          type: get_value(map, :type),
          amount: get_value(map, :amount),
          currency: get_value(map, :currency),
          status: get_value(map, :status),
          updated: get_value(map, :updated),
          fee: get_value(map, :fee),
          network: get_value(map, :network),
          comment: get_value(map, :comment),
          internal: get_value(map, :internal)
        }
      end

      defoverridable from_map: 1
    end
  end
end
